# Generated by Django 6.0.7 on 2026-07-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cliente / Experiencia',
                'verbose_name_plural': 'Clientes / Experiencias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='Lista de logros: ["Feature 1", "Feature 2"]'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='contact_message',
            field=models.TextField(blank=True, help_text='Texto de la sección de contacto al final del home'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='contact_title',
            field=models.CharField(default='¿Qué estás esperando?', max_length=120),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='cv_url',
            field=models.URLField(blank=True, help_text='Enlace al CV en PDF'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='skills_note',
            field=models.CharField(blank=True, help_text='Nota bajo skills, ej. "*Actualmente aprendiendo Next.js"', max_length=255),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=list, help_text='Links extra: [{"label": "GitHub", "url": "https://..."}]'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Número con código de país, sin + (ej. 521234567890)', max_length=20),
        ),
    ]
