# Generated by Django 6.0.7 on 2026-08-06 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_client_project_highlights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='cv_url',
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='cv_file',
            field=models.FileField(blank=True, help_text='CV en PDF. Se muestra como botón de descarga en el home.', upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
