# Generated by Django 6.0.7 on 2026-08-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_replace_cv_url_with_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='Lista de logros: ["Feature 1", "Feature 2"]'),
        ),
        migrations.AddField(
            model_name='client',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list, help_text='["React", "Django"]'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Nombre del cliente o del proyecto', max_length=120),
        ),
        migrations.AlterField(
            model_name='client',
            name='website_url',
            field=models.URLField(blank=True, help_text='Enlace al sitio del cliente'),
        ),
    ]
