# Generated by Django 6.0.7 on 2026-08-07 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_enrich_client_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='preview_image',
            field=models.FileField(blank=True, help_text='Captura o preview del proyecto. Se muestra a la derecha en la tarjeta.', upload_to='clients/previews/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
