# Generated by Django 6.0.7 on 2026-08-07 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_client_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.AddField(
            model_name='project',
            name='preview_image',
            field=models.FileField(blank=True, help_text='Captura o preview del proyecto. Se muestra en la tarjeta.', upload_to='projects/previews/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
